package br.com.velhatech.components.dialog.enums

enum class EnumVelhaTechMessageDialogTestTags {
    VELHA_TECH_MESSAGE_DIALOG,
    VELHA_TECH_MESSAGE_DIALOG_TITLE,
    VELHA_TECH_MESSAGE_DIALOG_MESSAGE,
    VELHA_TECH_MESSAGE_DIALOG_OK_BUTTON,
    VELHA_TECH_MESSAGE_DIALOG_CONFIRM_BUTTON,
    VELHA_TECH_MESSAGE_DIALOG_CANCEL_BUTTON
}